export default {
  "login": "Ajeet-jha",
  "id": 49264063,
  "node_id": "MDQ6VXNlcjQ5MjY0MDYz",
  "avatar_url": "https://avatars.githubusercontent.com/u/49264063?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Ajeet-jha",
  "html_url": "https://github.com/Ajeet-jha",
  "followers_url": "https://api.github.com/users/Ajeet-jha/followers",
  "following_url": "https://api.github.com/users/Ajeet-jha/following{/other_user}",
  "gists_url": "https://api.github.com/users/Ajeet-jha/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Ajeet-jha/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Ajeet-jha/subscriptions",
  "organizations_url": "https://api.github.com/users/Ajeet-jha/orgs",
  "repos_url": "https://api.github.com/users/Ajeet-jha/repos",
  "events_url": "https://api.github.com/users/Ajeet-jha/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Ajeet-jha/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Ajeet kumar jha",
  "company": null,
  "blog": "",
  "location": "New Delhi India",
  "email": null,
  "hireable": null,
  "bio": "Front-End Developer \r\nUI Developer\r\nWeb Developer\r\nHTML CSS JS JQUERY REACT ",
  "twitter_username": null,
  "public_repos": 50,
  "public_gists": 0,
  "followers": 0,
  "following": 11,
  "created_at": "2019-04-04T05:25:11Z",
  "updated_at": "2021-03-13T10:22:48Z"
}